blog/accounts/urls.py
from django.urls import path, include
from . import views

app_name = "users"

urlpatterns = [
    path('auth/', views.auth, name = "auth"),
    path('logout/', views.user_logout, name = "logout"),
    path('register/', views.user_register, name = "register"),
    path('login/', views.auth, name = "auth"),

]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('post.urls', namespace = "posts")),
    path('accounts/', include('accounts.urls', namespace = "users"))
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/post/urls.py
from django.urls import path
from . import views

app_name = "posts"

urlpatterns = [
    path('', views.home, name = "home"),
    path('post/<int:post_id>/', views.post, name = "post"),
    path('add-comment/<int:post_id>/', views.add_comment, name = "addcomment"),
    path('like/<int:post_id>', views.like, name = "like"),
    path('delete/<int:comment_id>', views.delete, name="delete"),
    path('all/', views.all, name = "all"),
    path('filter/', views.filter, name="filter"),
]

blog/post/models.py
from django.db import models
from django import forms
from django.contrib.auth.models import User
#from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField

import os
import random
import string

def user_directory_path(instance, filename):
    ext = filename.split('.')[-1]
    letters = string.ascii_letters
    random_string = ''.join(random.choice(letters) for i in range(10))
    filename = "%s_%s.%s" % (instance.title, random_string, ext)
    return os.path.join('post_images/', filename)

class Post(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    title = models.CharField(max_length = 255)
    content = RichTextUploadingField(blank = True, null = True)
    preview = models.CharField(max_length = 1000)
    thumbnail  = models.FileField(upload_to = user_directory_path, default = "none.jpg")
    date = models.DateField(auto_now = False, auto_now_add = True)
    last_edit = models.DateField(auto_now = True, auto_now_add = False)
    number_of_likes = models.IntegerField(default = 0)
    number_of_comments = models.IntegerField(default = 0)
    tags = models.CharField(max_length = 1000)

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete = models.CASCADE)
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    text = models.CharField(max_length = 1000)

    def __str__(self):
        return self.post.title

class Like(models.Model):
    post = models.ForeignKey(Post, on_delete = models.CASCADE)
    user = models.ForeignKey(User, on_delete = models.CASCADE)

    def __str__(self):
        return self.post.title

blog/post/views.py
from django.shortcuts import render
from .models import Post, Comment, Like
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse

def home(request):
    last_posts = []
    posts = Post.objects.all().order_by('-date')
    for i in range(2):
        last_posts.append(posts[i])
    context = {'posts' : last_posts}
    return render(request, 'posts/home.html', context)

def all(request):
    posts = Post.objects.all()
    context = {'posts' : posts}
    return render(request, 'posts/all.html', context)

def filter(request):
    requested_filters = request.GET.getlist('filter[]')
    posts = Post.objects.all()
    filtered_posts = {}
    matching = 0
    for post in posts:
        post_tags = post.tags.split(",")
        for filter in requested_filters:
            if filter in post_tags:
                matching += 1
        if matching >= 1:
            filtered_posts[post] = matching
        matching = 0
    new_list = sorted(filtered_posts, key = filtered_posts.get, reverse = True)
    context = {'posts' : new_list}
    return render(request, 'posts/all.html', context)

def post(request, post_id):
    selected_post = Post.objects.get(pk = post_id)
    selected_post.number_of_comments = len(Comment.objects.filter(post = selected_post.id))
    selected_post.save()
    comments = Comment.objects.filter(post = selected_post)
    user_authenticated = False
    context = {}
    liked = False
    if request.user.is_authenticated:
        user_authenticated = True
        user = User.objects.get(pk = request.user.id)
        if (Like.objects.filter(post = selected_post, user = user).exists()):
            liked = True
        else:
            liked = False
    context['is_liked'] = liked
    context['post'] = selected_post
    context['comments'] = comments
    context['user_authenticated'] = user_authenticated
    return render(request, 'posts/post.html', context)

@csrf_exempt
def add_comment(request, post_id):
    if request.method == "POST" and request.user.is_authenticated:
        u_pk = request.user.id
        comment_text = request.POST['comment_text']
        post = Post.objects.get(pk=post_id)
        comment = Comment(user = User.objects.get(pk=u_pk), post = post, text = comment_text)
        comment.save()
        post.number_of_comments += 1
        post.save()
        response = JsonResponse({'a' : "a"})
        return response
@csrf_exempt
def like(request, post_id):
    if request.user.is_authenticated:
        post = Post.objects.get(pk=post_id)
        user = User.objects.get(pk=request.user.id)
        if (Like.objects.filter(post = post, user = user).exists()):
            response = JsonResponse({'unliked' : True})
            Like.objects.filter(post=post, user=user).delete()
            post.number_of_likes = post.number_of_likes - 1
            post.save()
            return response
        else:
            like = Like(post = post, user=user)
            like.save()
            post.number_of_likes = post.number_of_likes + 1
            post.save()
            response = JsonResponse({'liked' : True})
            return response
    else:
        response = JsonResponse({'error' : 'User not loged in'})
        reponse.status_code = 403
        return response

def delete(request, comment_id):
    post_id = 0
    if request.user.is_authenticated:
        comment = Comment.objects.filter(pk=comment_id)
        if comment.exists():
            post_id = comment[0].post.id
            comment.delete()

    url = reverse('posts:post', kwargs={'post_id' : post_id})
    return HttpResponseRedirect(url)

blog/post/templates/posts/all.html
{% extends 'base.html'%}
{% load static %}
{% block logout_button %}
	{% if user.is_authenticated %}
		<a id="logout_button" href="{% url 'users:logout' %}">Logout</a>
	{% endif %}
{% endblock %}
{% block content %}
	<div class="filters">
		<p id="show_filters" onclick="showFilters()">Filter tag</p>
		<div id="filter">
			<form class="" action="{% url 'posts:filter' %}" method="GET">
				<input type="checkbox" name="filter[]" value="science">Science
				<input type="checkbox" name="filter[]" value="programming">Programming
				<input type="checkbox" name="filter[]" value="cars">Cars
				<input type="checkbox" name="filter[]" value="space">Space
				<input type="checkbox" name="filter[]" value="tech">Tech
				<input type="checkbox" name="filter[]" value="traveling">Traveling
				<input type="submit" name="submit" id="filters_submit" value="Filter">
			</form>
		</div>
	</div>
	<main>
		<section id="all_posts">
	            <div class="container">
	                  {% for post in posts %}
	                        <a class="post"href="{% url 'posts:post' post.pk %}">
	                              <div>
	                                    <h2>{{post.title|safe}}</h2>
	                                    <p id="preview">{{post.preview|safe}}</p>
	                                    <p id="publish_info">Published on {{post.date|date:"d M Y"}} by {{post.user.username}}</p>
	                              </div>
	                        </a>
	                  {% endfor %}
	            </div>
	      </section>
	</main>
{% endblock %}

{% block custom_script %}
      <script type="text/javascript">
		function showFilters(){
			var filter = document.getElementById("filter");
			var filter_button = document.getElementById("show_filters");
			filter.style.display = "block";
			filter_button.style.display = "none";
		}

            function remove_signup(){
                  document.getElementById("signup").style.display = "none";
                  document.getElementById("signup").style.width = "0";
                  document.getElementById("header_content").style.width = "100%";
                  document.getElementById("content").style.width = "100%";
            }
            {% if user.is_authenticated %}
                  remove_signup();
            {% endif %}
            $('#login_form').on('submit', function(e){
			e.preventDefault();
			var data = new FormData($('#login_form')[0]);
			$.ajax({
				url: "{% url 'users:auth' %}",
				type: "POST",
				data: data,
				cache: data,
				dataType: 'json',
				processData: false,
				contentType: false,
				success: function(data){
					if (data['logedin'] == "True"){
						remove_signup();
					}
					else if (data['wrong_credentials'] == "True"){
                                    document.getElementById("uname_input").style.border = "1px solid red";
                                    document.getElementById("pw_input").style.border = "1px solid red";
                                    document.getElementById("error_paragraph").innerHTML = "Wrong credentials";
					}
				},
				error: function(data){
					alert("Something went wrong.")
				}
			});
		});
            $('#user_reg_form').on('submit', function(e){
      		e.preventDefault();
                  var data = new FormData($('#user_reg_form')[0]);
      		$.ajax({
      			url : "{% url 'users:register' %}",
      			type: "POST",
      			data: data,
      			cache: data,
      			dataType: 'json',
      			processData: false,
      			contentType: false,
      			success: function(data){
      				if (data['success'] == "true"){
      					remove_signup();
      				}else {
                                    console.log(data['error'])
                                    document.getElementById("error_paragraph_register").innerHTML = data['error'];
      				}
      			},
      		});
      	});
      </script>
{% endblock %}

blog/post/templates/posts/home.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block logout_button %}
      {% if user.is_authenticated %}
            <a href="{% url 'users:logout' %}">Logout</a>
      {% endif %}
{% endblock %}
{% block content %}
      <header style = "background: url({% static '/img/header.jpg' %}); background-size: cover; height: 600px;">
            <div id="header_content">
                  <div id="content">
                        <p id="huge_welcome">Welcome to my blog</p>
                        <p id="normal">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                  </div>
            </div>
            <div id="signup">
                  <div class="select_signup">
                        <button type="button" name="button" onclick="show_login_form()">Login</button>
                        <button type="button" name="button" onclick="show_register_form()">Register</button>
                  </div>
                  <div id="login">
                        <p id="error_paragraph"></p>
                        <form id="login_form" action="{% url 'users:auth' %}" method="post">
                              {% csrf_token %}
                              <input type="text" name="username" placeholder="Username" value="">
                              <input type="password" name="password" placeholder="Password" value="">
                              <input type="submit" name="" value="Done">
                        </form>
                  </div>
                  <div id="register">
                        <p id="error_paragraph_register"></p>
                        <form id="register_form" action="{% url 'users:register' %}" method="post">
                              {% csrf_token %}
                              <input type="text" name="username" placeholder="Username" value="">
                              <input type="text" name="email" placeholder="E-mail" value="">
                              <input type="password" name="password" placeholder="Password" value="">
                              <input type="password" name="repeat_password" placeholder="Repeat password" value="">
                              <input type="submit" name="" value="Done">
                        </form>
                  </div>
            </div>
      </header>
      <main>
            <section id = "latestPost">
                  <div class="container">
                        {% for post in posts %}
                              <a href="{% url 'posts:post' post.pk %}">
                                    <div class="post">
                                          <h1>{{post.title|safe}}</h1>
                                          <p>{{post.preview|safe}}</p>
                                          <p id="publish_info">Published on {{post.date|date:"M, d Y"}} by {{post.user.username}}</p>
                                    </div>
                              </a>
                        {% endfor %}
                        <a id="older_posts_a" href="{% url 'posts:all' %}">All posts</a>
                  </div>
            </section>
      </main>
{% endblock %}
{% block custom_script %}
      <script type="text/javascript">
            var login_form = document.getElementById("login");
            var register_form = document.getElementById("register");
            var user_auth = "{{user.is_authenticated}}";
            function remove_signup(){
                  document.getElementById("signup").style.display = "none";
                  document.getElementById("header_content").style.width = "100%";
            }
            function show_login_form(){
                  login_form.style.display = "block";
                  register_form.style.display = "none";
            }
            function show_register_form(){
                  login_form.style.display = "none";
                  register_form.style.display = "block";
            }

            if (user_auth == "True"){
                  remove_signup();
            } else {
                  document.getElementById("signup").style.display = "block";
                  document.getElementById("header_content").style.width = "60%";
            }


            $("#register_form").on("submit", function(e){
                  e.preventDefault();
                  var data = new FormData($("#register_form")[0]);
                  $.ajax({
                        url: "{% url 'users:register' %}",
                        type: "POST",
                        data: data,
                        cache: data,
                        processData: false,
                        contentType: false,
                        success: function(data){
                              if (data['success'] == true){
                                    remove_signup();
                              }else if (data['error']){
                                    document.getElementById("error_paragraph_register").innerHTML = data['error'];
                              }
                        }
                  });
            });

            $("#login_form").on("submit", function(e){
                  e.preventDefault();
                  var data = new FormData($("#login_form")[0]);
                  $.ajax({
                        url: "{% url 'users:auth' %}",
                        type: "POST",
                        data: data,
                        cache: data,
                        processData: false,
                        contentType: false,
                        success: function(data){
                              console.log(data);
                              if (data['logedin'] == true){
                                    remove_signup();
                              }else if (data['wrong_credentials'] == true){
                                    document.getElementById("error_paragraph").innerHTML = "Wrong credentials";
                              }
                        }
                  });
            });

      </script>
{% endblock %}

blog/post/templates/posts/post.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block logout_button %}
	{% if user.is_authenticated %}
		<a href="{% url 'users:logout' %}">Logout</a>
	{% endif %}
{% endblock %}
{% block content %}
	<section class="post-section">
		<div style="background: url('{{post.thumbnail.url}}'); height: 700px; background-size: cover; margin: 0; padding-top: 20px;">
			<div class="post-title-date">
				<h1>{{post.title|safe}}</h1>
				<p>Published on {{post.date|date:"M, d Y"}} by {{post.user.username}}</p>
			</div>
		</div>
		<div class="post-content">
            	{{post.content|safe}}
		</div>
	</section>
	<div class="login-popup-form" id="popup-login">
		<form class="form-container" action="{% url 'users:auth' %}" method="post" id="login_form">
			{% csrf_token %}
			<input id="uname_field" type="text" name="username" placeholder="Enter your username">
			<input id="pw_field" type="password" name="password" placeholder="Enter your password">
			<input type="submit" name="submit" value="LOGIN">
		</form>
		<button class="btn_cancel" value="CLOSE" onclick="close_form()">CLOSE</button>
	</div>
	<section id="user-options">
		<div class="container">
			<a href="" id="like_button"><i id="like-button" class="fa-heart"></i></a>
			<p id="number_of_likes">{{post.number_of_likes|safe}}</p>
			<a href="" id="comment-button"><i class="fas fa-comment"></i></a>
			<p id="number_of_comments">{{post.number_of_comments|safe}}</p>
		</div>
	</section>
	<section id="comments">
		<div id="comments-div">
			<div id="comment-form">
				<form id="form_comment" class="form-comment" action="{% url 'posts:addcomment' post.pk %}" method="post">
					{% csrf_token %}
					<input id="comment_text_input" type="text" name="comment_text" value="" placeholder="Comment">
					<input id="comment-submit-button" type="submit" name="done-button" value="Done">
				</form>
			</div>
			<div class="contasiner">
				{% for comment in comments %}
					<div class="comment">
						<div class="comment-author"><p>{{comment.user}} says:</p></div>
						<div class="comment-text"><p>{{comment.text}}</p></div>
						{% if comment.user == user %}
							<a href="{% url 'posts:delete' comment.pk %}"><i class="fas fa-trash-alt"></i></a>
						{% endif %}
					</div>
				{% endfor %}
			</div>
		</div>
	</section>
{% endblock %}
{% block custom_script %}
	<script type="text/javascript">
		var user_auth = "{{user.is_authenticated}}";
		var is_liked = "{{is_liked}}";
		var like_button = document.getElementById("like-button");
		var like_count = document.getElementById("number_of_likes");
		console.log(is_liked);
		if (is_liked == "False"){
			like_button.classList.add('far');
			like_button.classList.remove('fas');
		}else {
			like_button.classList.add('fas');
			like_button.classList.remove('far');
		}
		function open_form(){
			document.getElementById("popup-login").style.display = "block";
		}
		function close_form(){
			document.getElementById("popup-login").style.display = "none";
		}
		$(document).on('click', '#comment-submit-button', function(e){
			e.preventDefault();
			var comment = document.getElementById("comment_text_input");
			if(/[a-zA-Z]/.test(comment.value) || /\d/.test(comment.value)){
				var data = new FormData($('#form_comment')[0]);
				$.ajax({
					url: "{% url 'posts:addcomment' post.pk %}",
					type: "POST",
					data: data,
					cache: data,
					processData: false,
					contentType: false,
					success: function(data){
						$('#comments').load("{% url 'posts:post' post.pk%}" + ' #comments-div');
						var noc = document.getElementById('number_of_comments').innerHTML;
						document.getElementById('number_of_comments').innerHTML = parseInt(noc) + 1;
					}
				});
			}else {
				comment.style.border = "1px solid red";
			}
		});
		$('#login_form').on('submit', function(e){
			e.preventDefault();
			var data = new FormData($('#login_form')[0]);
			$.ajax({
				url: "{% url 'users:auth' %}",
				type: "POST",
				data: data,
				cache: data,
				dataType: 'json',
				processData: false,
				contentType: false,
				success: function(data){
					if (data['logedin'] == true){
						location = "{% url 'posts:post' post.pk %}";
						user_auth = "True";
						close_form();
					}
					else if (data['logedin'] == false){
						document.getElementById("uname_field").style.border = "1px solid red";
						document.getElementById("pw_field").style.border = "1px solid red";
						open_form();
					}
				},
				error: function(data){
					alert("Something went wrong.")
				}
			});
		});
		$('#comment-button').on('click', function(e){
			e.preventDefault();
			if (user_auth == "True"){
				document.getElementById("comment-form").style.display = "block";
			}else if (user_auth = "False"){
				open_form();
			}
		});
		$('#like_button').on('click', function(e){
			e.preventDefault();
			var data = {
				key: "csrfmiddlewaretoken",
				value: "{{csrf_token}}"
			};
			if (user_auth == "True"){
				$.ajax({
					url: "{% url 'posts:like' post.pk %}",
					data: data,
					type: "POST",
					success: function(data){
						var likes = document.getElementById('number_of_likes').innerHTML;
						if (data['unliked'] == true){
							like_count.innerHTML = parseInt(likes) - 1;
							like_button.classList.add('far');
							like_button.classList.remove('fas');
						}else if (data['liked'] == true){
							like_count.innerHTML = parseInt(likes) + 1;
							like_button.classList.add('fas');
							like_button.classList.remove('far');
						}
					}
				});
			}else if (user_auth = "False"){
				open_form();
			}
		});

	</script>
{% endblock %}